name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches:
      - main
      - "feature/**"
      - "bugfix/**"

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  basic-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show files
        run: ls -la

      - name: Basic validation
        run: echo "CI is working"
